language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

services:
script:
  - pipenv shell
  - ./sparkpostSMIME.py -h
  - ./mimeshow.py -h
  - py.test

branches:
  only:
    - master