language: python
python:
# "3.4" giving pathlib error with pytest: ImportError: No module named 'pathlib2'
  - "3.5"
  - "3.6"
# "3.7" not yet available in travis ci env

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev


before_script:
  # ensure that main module is available for import during tests
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  # basic tests - command line tools are installed and give help/usage
  - ./sparkpostSMIME.py -h
  - ./mimeshow.py -h
  - ./readSMIMEsig.py -h
  # internal test cases. Invoke pytest where it can find the cert files
  - cd tests; pytest

branches:
  only:
    - master