language: python
python:
# "3.4" giving pathlib error with pytest: ImportError: No module named 'pathlib2'
  - "3.5"
  - "3.6"
# "3.7" not yet available in travis ci env

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

services:
script:
  - pipenv run ./sparkpostSMIME.py -h
  - pipenv run ./mimeshow.py -h
# internal test cases. Invoke pytest including access to current project dir
  - pipenv run python -m pytest

branches:
  only:
    - master