language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
services:
script:
  - pipenv run ./sparkpostSMIME.py -h
  - pipenv run ./mimeshow.py -h

branches:
  only:
    - master