language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# "3.7" not yet available in travis

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

services:
script:
  - pipenv run ./sparkpostSMIME.py -h
  - pipenv run ./mimeshow.py -h
# internal test cases
  - pipenv run python -m pytest

branches:
  only:
    - master